[package]
name = "pm-config"
version = "0.1.0"
edition = "2024"

[dependencies]
error-location = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
log = { workspace = true }
toml = { workspace = true }
dirs = { workspace = true }
