[package]
name = "pm-core"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = { workspace = true }
error-location = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }

pm-proto = { workspace = true }
